#! /bin/bash

HOST_FOLDER="../laotzes-dialogues" 

CONTAINER_NAME="dialogues"

CONTAINER_PREFIX="/data/posts/"

find "$HOST_FOLDER" -type f -mmin -20 -print0 | while IFS= read -r -d '' file; do

    RELATIVE=$(realpath --relative-to="$HOST_FOLDER" "$file")
    
    FULL_INTERNAL_PATH="${CONTAINER_PREFIX}${RELATIVE}"
    
    echo "$FULL_INTERNAL_PATH"

done | docker exec -i "$CONTAINER_NAME" flask save
