#! /bin/bash

posts_location=~/projects/laotzes-dialogues
project_folder=~/projects/dialogues

cd $project_folder

ls -r  "$posts_location/en/"* | python -m utility.process_posts
ls -r  "$posts_location/es/"* | python -m utility.process_posts
