#! /bin/bash

file=translations/es/LC_MESSAGES/messages.po

pybabel extract -F babel.cfg -o messages.pot .
pybabel update -i messages.pot -d translations

$EDITOR  $file

pybabel compile -d translations
